# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - test-decentralized-identity

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_d38e53dd8fd3497f8f7fcf86d4ad5383 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e9f6ae1b1e094264ae6fc2d87fd26374 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.AzureAppService_ContainerUsername_d38e53dd8fd3497f8f7fcf86d4ad5383 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'test-decentralized-identity'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_fefb2ae97f424cf483a491edfb7f46d2 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_d38e53dd8fd3497f8f7fcf86d4ad5383 }}/appsvc/staticsite:${{ github.sha }}'